#!/usr/bin/python

import socket, ssl, pprint

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
ssl_sock = ssl.wrap_socket(s, cert_reqs=ssl.CERT_REQUIRED, ca_certs='/home/sven/ssl/allowed')
ssl_sock.connect(('localhost', 9151))

ssl_sock.write('test data')

ssl_sock.close()
